### ISSUE TITLE
core/Enrich.py has a error

### ISSUE THREAD

**Issue by maciejurm** [GetStream/Stream-Example-Py#16]
Hi, 
I have no idea how where it came for current_user in core/Enrich.py 

Another error also appers:
"argument of type 'QuerySet' is not iterable" when i try build follow button in user profile.

**Comment by dwightgunning** [comment]
Can you clarify the error that you receive from Enrich.py? Feel free to attach a stack trace.

**Comment by dwightgunning** [comment]
Closing as without additional information there isn't too much more we can assist with here. Happy to re-open if new information comes to light.
