### ISSUE TITLE
OfflineGenerationError at /

### ISSUE THREAD

**Issue by rohitchopra32** [GetStream/Stream-Example-Py#17]
Request Method: | GET
-- | --
http://127.0.0.1:8000/
1.10.8
OfflineGenerationError
You have offline compression enabled but key "e99a199cb21dcd21097170603d674b43f5d5f62d585da36ebeccd461ba366791" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:   			<link rel="stylesheet" href="/static/css/style.scss" type="text/x-scss" charset="utf-8">
/home/rohit/Desktop/projects/extraenv/lib/python3.6/site-packages/compressor/templatetags/compress.py in render_offline, line 75
/home/rohit/Desktop/projects/extraenv/bin/python
3.6.3
['/home/rohit/Desktop/projects/Stream-Example-Py',  '/home/rohit/Desktop/projects/extraenv/lib/python36.zip',  '/home/rohit/Desktop/projects/extraenv/lib/python3.6',  '/home/rohit/Desktop/projects/extraenv/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/rohit/Desktop/projects/extraenv/lib/python3.6/site-packages',  '/home/rohit/Desktop/projects/Opentok-Python-SDK-master']
Wed, 2 May 2018 06:52:47 +0000

**Comment by dwightgunning** [comment]
Per the error, you'll just need to run the django-compressor offline build. The command is `python manage.py compress`.

This should be in the `install.MD` file. I'll add that.

**Comment by dwightgunning** [comment]
Resolved with 42b57ba.
