### ISSUE TITLE
"Sign in with Github" 500's

### ISSUE THREAD

**Issue by ACollectionOfAtoms** [GetStream/Stream-Example-Py#18]
At least it does for me! 

Clicking on any of the 

http://exampledjango.getstream.io/accounts/github/login/?process=login

Links

results in 500

**Comment by dwightgunning** [comment]
Thanks for bringing this to our attention. We'll take a look.

**Comment by douglaspetrin** [comment]
This is still happening: **Server Error (500)**

**Comment by tbarbugli** [comment]
Fixed it now, thank you for letting us know about it!
