### ISSUE TITLE
stream_django vs stream_framework

### ISSUE THREAD

**Issue by cliff28** [GetStream/Stream-Example-Py#8]
I am having a hard time determining the difference between these two. Is it simply that stream_django is a hosted (paid) version while stream_framework is not?

**Comment by tbarbugli** [comment]
stream_framework is an open source framework (written Python) to build scalable feeds. stream_django is an integration library to use [getstream.io](https://getstream.io), a service to build scalable feeds, with Django.

Thank you for pointing this out. I am going to see how we can make this distinction more clear in the project readme.
